version: '3.8'

services:
  mumble-recorder:
    build: .
    container_name: mumble-recorder
    env_file:
      - .env.local
    volumes:
      - ./recordings:/recordings
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mumble-recorder-web:
    build: .
    container_name: mumble-recorder-web
    entrypoint: ["python", "-m", "mumble_recorder.web"]
    environment:
      - OUTPUT_DIR=/recordings
      - WEB_PORT=5000
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    volumes:
      - ./recordings:/recordings
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
